; generated by PrusaSlicer
; postprocessed: 2026-06-30T16:36:48
; --- E5S1 postprocess ---
; extruder_clearance_height = 20
; first_layer_height = 0.24
; layer_height = 0.2
; total_layer_count = 2

G28 ; postprocess homing
M420 S1 Z10 ; postprocess mesh
M109 S215 ; postprocess wait hotend
G1 X2.0 Y20 F5000.0 ; postprocess purge
G1 Z0.240 F1500.0 ; postprocess purge
G1 X2.0 Y145.0 Z0.240 F1500.0 E12.47 ; postprocess purge
G1 X2.3 Y145.0 Z0.240 F5000.0 ; postprocess purge
G1 X2.3 Y20 Z0.240 F1500.0 E24.95 ; postprocess purge
G92 E0 ; postprocess purge
; postprocess skirt
G1 Z0.24 F600 ; postprocess skirt
G1 X3.0 Y3.0 F6000 ; postprocess skirt
G1 X43.0 Y3.0 E4.00 F600 ; postprocess skirt
G1 X43.0 Y43.0 E4.00 F600 ; postprocess skirt
G1 X3.0 Y43.0 E4.00 F600 ; postprocess skirt
G1 X3.0 Y3.0 E4.00 F600 ; postprocess skirt
G1 X2.0 Y2.0 F6000 ; postprocess skirt
G1 X45.0 Y2.0 E4.30 F600 ; postprocess skirt
G1 X45.0 Y45.0 E4.30 F600 ; postprocess skirt
G1 X2.0 Y45.0 E4.30 F600 ; postprocess skirt
G1 X2.0 Y2.0 E4.30 F600 ; postprocess skirt
G1 X2.0 Y2.0 F6000 ; postprocess skirt
G1 X47.0 Y2.0 E4.50 F600 ; postprocess skirt
G1 X47.0 Y47.0 E4.50 F600 ; postprocess skirt
G1 X2.0 Y47.0 E4.50 F600 ; postprocess skirt
G1 X2.0 Y2.0 E4.50 F600 ; postprocess skirt
M900 K0.08 ; linear advance postprocess
G92 E0 ; postprocess skirt
G1 X10 Y10 F600
;TYPE:External perimeter
M106 S0 ; fan adhesion postprocess
G1 X20 Y10 F1200
;TYPE:Overhang
M106 S216 ; fan overhang postprocess
G1 X20 Y20 F1200
