; generated by PrusaSlicer
; postprocessed: 2026-06-29T19:57:07
; --- E5S1 postprocess ---
G28
M104 S210
M109 S210
G1 X2.0 Y20 F5000.0 ; postprocess purge
G1 Z0.28 F1500.0 ; postprocess purge
G1 X2.0 Y145.0 Z0.28 F1500.0 E15 ; postprocess purge
G1 X2.3 Y145.0 Z0.28 F5000.0 ; postprocess purge
G1 X2.3 Y20 Z0.28 F1500.0 E30 ; postprocess purge
G92 E0 ; postprocess purge
; postprocess skirt
G1 Z0.24 F600 ; postprocess skirt
G1 X3.0 Y3.0 F6000 ; postprocess skirt
G1 X43.0 Y3.0 E4.00 F600 ; postprocess skirt
G1 X43.0 Y43.0 E4.00 F600 ; postprocess skirt
G1 X3.0 Y43.0 E4.00 F600 ; postprocess skirt
G1 X3.0 Y3.0 E4.00 F600 ; postprocess skirt
G1 X5.0 Y5.0 F6000 ; postprocess skirt
G1 X45.0 Y5.0 E4.00 F600 ; postprocess skirt
G1 X45.0 Y45.0 E4.00 F600 ; postprocess skirt
G1 X5.0 Y45.0 E4.00 F600 ; postprocess skirt
G1 X5.0 Y5.0 E4.00 F600 ; postprocess skirt
G1 X7.0 Y7.0 F6000 ; postprocess skirt
G1 X47.0 Y7.0 E4.00 F600 ; postprocess skirt
G1 X47.0 Y47.0 E4.00 F600 ; postprocess skirt
G1 X7.0 Y47.0 E4.00 F600 ; postprocess skirt
G1 X7.0 Y7.0 E4.00 F600 ; postprocess skirt
M900 K0.06 ; linear advance postprocess
G92 E0 ; postprocess skirt
G1 Z0.24 F600
G29
;BEFORE_LAYER_CHANGE
M221 S100 ; postprocess flow L1
M106 S0 ; fan postprocess layer 1
M204 S500 ; postprocess accel
G92 E0
;LAYER_CHANGE
;LAYER:0
G1 X10 Y10 E1.0 F1200
;TYPE:External perimeter
M106 S0 ; fan adhesion postprocess
G1 X20 Y20 E2.0 F1200
G1 Z0.4 F600 ; postprocess z hop
G1 E-0.8 F2700 ; postprocess layer retract
;BEFORE_LAYER_CHANGE
M221 S90 ; postprocess flow L2
M106 S0 ; fan postprocess layer 2
M204 S500 ; postprocess accel
G92 E0
;LAYER_CHANGE
;LAYER:1
;TYPE:External perimeter
M106 S0 ; fan adhesion postprocess
G1 X20 Y20 E3.0 F1200
