"""G-code transform loop — Prusa geometry in, E5S1 machine params out."""
from __future__ import annotations

import re
import abc
from datetime import datetime

from config import (
    LAYER_BEFORE_MARKER,
    LAYER_CHANGE_MARKER,
    LAYER_RETRACT,
    MARKER,
    M204_CAP_LAYERS,
    PA_PROBE_LINES,
    AFTER_LAYER_MARKER,
)
from gcode_patterns import F_RE, FAN_ON_RE, G1_EXTRUDE_RE, M204_S_RE, strip_pp_lines
from gcode_emit import GCodeBuilder
from gcode_features import GCodeFeatureScanner
from gcode_repair import inject_pa, repair_gcode
from gcode_tune import (
    SpeedTuner,
    RetractionTuner,
    FanSpeedTuner,
    fan_pwm_for_layer,
    sanitize_startup_line,
)
from profile import E5S1Profile, build_e5s1_profile, resolve_pa_firmware
from bundle_config import get_bundle_config


class TransformContext:
    def __init__(self, profile: E5S1Profile, builder: GCodeBuilder, skip_overhang_fan: bool):
        self.profile = profile
        self.builder = builder
        self.skip_overhang_fan = skip_overhang_fan
        self.out: list[str] = []
        self.actions: list[str] = []
        self.layer_count = 0
        self.in_startup = True
        self.layer_fan_cap: int | None = None
        self.boost_fan = False
        self.cool_boost = False
        self.flow_bridge = False
        self.surface_kind: str | None = None
        self.last_f = profile["default_motion_f"]
        self.skip_fan_at: set[int] = set()
        
        self.speed_tuner = SpeedTuner()
        self.retraction_tuner = RetractionTuner()
        self.fan_speed_tuner = FanSpeedTuner()
        
        self.current_line = ""
        self.current_upper = ""

    def update_line(self, line: str) -> None:
        self.current_line = line
        self.current_upper = line.upper()

    def reset_flow(self) -> None:
        if self.flow_bridge:
            self.out.append(self.builder.flow_reset())
            self.actions.append("flow_reset")
            self.flow_bridge = False

    def restore_layer_fan(self) -> None:
        if self.layer_fan_cap is not None:
            self.out.append(self.builder.fan_restore(self.layer_fan_cap))
            self.actions.append("fan_restore")

    def begin_layer(self, stripped: str) -> None:
        self.layer_count += 1
        cap = fan_pwm_for_layer(self.layer_count, self.profile)
        self.out.append(stripped)
        ramp = self.profile["flow_ramp"]
        if self.layer_count <= len(ramp):
            flow = ramp[self.layer_count - 1]
            self.out.append(self.builder.flow_layer(self.layer_count, flow))
            self.actions.append(f"flow_l{self.layer_count}_S{flow}")
        elif self.layer_count == len(ramp) + 1:
            self.out.append(self.builder.flow_reset())
            self.actions.append("flow_reset")
        if cap is not None:
            self.out.append(self.builder.fan_layer(cap, self.layer_count))
            self.actions.append(f"fan_l{self.layer_count}_pwm_{cap}")
        if self.layer_count <= self.profile["first_layer_motion_layers"]:
            self.out.append(self.builder.accel(self.profile["first_layer_accel"]))
            self.actions.append(f"accel_l{self.layer_count}")
        elif self.layer_count == self.profile["first_layer_motion_layers"] + 1:
            self.out.append(self.builder.accel(self.profile["default_accel"]))
            self.actions.append(f"accel_default_l{self.layer_count}")
        self.layer_fan_cap = cap


class ILineTransformer(abc.ABC):
    @abc.abstractmethod
    def transform(self, ctx: TransformContext, lines: list[str], idx: int) -> bool:
        """Returns True if the line was fully handled and the pipeline should move to the next line."""
        pass


class SpeedTrackingTransformer(ILineTransformer):
    def transform(self, ctx: TransformContext, lines: list[str], idx: int) -> bool:
        if ctx.current_upper.startswith(("G0", "G1")) and (fm := F_RE.search(ctx.current_line)):
            ctx.last_f = int(fm.group(1))
        return False


class StartupLineTransformer(ILineTransformer):
    def transform(self, ctx: TransformContext, lines: list[str], idx: int) -> bool:
        if ctx.in_startup:
            fixed, fix_action = sanitize_startup_line(ctx.current_line, ctx.profile["first_layer_height_mm"])
            if fix_action:
                ctx.actions.append(fix_action)
            if fixed is None:
                return True
            if fixed != ctx.current_line:
                ctx.update_line(fixed)
        return False


class HeaderTransformer(ILineTransformer):
    def transform(self, ctx: TransformContext, lines: list[str], idx: int) -> bool:
        if ctx.current_line.startswith("; generated by"):
            ctx.out += [ctx.current_line, ctx.builder.timestamp(datetime.now().isoformat(timespec="seconds")), MARKER]
            ctx.actions.append("header")
            return True
        return False


class FeatureTypeTransformer(ILineTransformer):
    def __init__(self):
        self.scanner = GCodeFeatureScanner()

    def transform(self, ctx: TransformContext, lines: list[str], idx: int) -> bool:
        feat = self.scanner.type_feature(ctx.current_line)
        if feat in ("bridge", "overhang"):
            if ctx.cool_boost:
                ctx.restore_layer_fan()
            ctx.reset_flow()
            ctx.out.append(ctx.current_line)
            if feat == "bridge":
                ctx.out.append(ctx.builder.flow_bridge(ctx.profile["bridge_flow_pct"]))
                ctx.actions.append("flow_bridge")
                ctx.flow_bridge = True
                ctx.out.append(ctx.builder.fan_bridge(ctx.profile["bridge_fan_pwm"]))
                ctx.actions.append("fan_bridge")
            elif not ctx.skip_overhang_fan:
                ctx.out.append(ctx.builder.fan_overhang(ctx.profile["overhang_fan_pwm"]))
                ctx.actions.append("fan_overhang")
            ctx.boost_fan = True
            ctx.cool_boost = True
            ctx.surface_kind = feat
            return True

        if feat is not None:
            ctx.reset_flow()
            if ctx.cool_boost:
                ctx.restore_layer_fan()
                ctx.cool_boost = False

            ctx.boost_fan = feat in ("top", "ironing", "interface", "support", "bottom", "external", "perimeter", "brim", "bridge", "overhang")

            if feat in ("external", "perimeter", "top", "ironing", "interface", "support", "bottom", "brim"):
                ctx.out.append(ctx.current_line)
                skip_idx = ctx.fan_speed_tuner.tune(
                    ctx.out, ctx.actions, feat, lines, idx, ctx.layer_count, ctx.layer_fan_cap, ctx.profile, ctx.builder
                )
                if skip_idx:
                    ctx.skip_fan_at.add(skip_idx)
                ctx.surface_kind = feat
                return True
            
            if feat == "other":
                ctx.surface_kind = None
                ctx.boost_fan = False
                return True

            ctx.out.append(ctx.current_line)
            ctx.surface_kind = feat
            return True
        
        return False


class IroningFanTransformer(ILineTransformer):
    def transform(self, ctx: TransformContext, lines: list[str], idx: int) -> bool:
        fan_m = FAN_ON_RE.match(ctx.current_line)
        if ctx.surface_kind == "ironing" and fan_m and "postprocess" not in ctx.current_line.lower():
            pwm = int(fan_m.group(1))
            if pwm != ctx.profile["ironing_fan_pwm"]:
                ctx.out.append(ctx.builder.fan_ironing(ctx.profile["ironing_fan_pwm"]))
                ctx.actions.append("fan_ironing")
            else:
                ctx.out.append(ctx.current_line)
            return True
        return False


class LayerBoundaryTransformer(ILineTransformer):
    def transform(self, ctx: TransformContext, lines: list[str], idx: int) -> bool:
        if LAYER_BEFORE_MARKER in ctx.current_line or AFTER_LAYER_MARKER in ctx.current_line:
            ctx.in_startup = False
            if ctx.cool_boost:
                ctx.restore_layer_fan()
            ctx.reset_flow()
            if LAYER_BEFORE_MARKER in ctx.current_line and LAYER_RETRACT and ctx.layer_count >= 1 and not ctx.retraction_tuner.recent_retract(ctx.out):
                ctx.out.extend(ctx.retraction_tuner.layer_retract_lines(ctx.profile, ctx.builder))
                ctx.actions.append("retract_layer")
            ctx.boost_fan = False
            ctx.cool_boost = False
            ctx.surface_kind = None
            ctx.begin_layer(ctx.current_line)
            return True
        if LAYER_CHANGE_MARKER in ctx.current_line:
            ctx.in_startup = False
            if ctx.layer_count == 0:
                if ctx.cool_boost:
                    ctx.restore_layer_fan()
                ctx.reset_flow()
                ctx.boost_fan = False
                ctx.cool_boost = False
                ctx.surface_kind = None
                ctx.begin_layer(ctx.current_line)
            else:
                ctx.out.append(ctx.current_line)
            return True
        return False


class AccelCapTransformer(ILineTransformer):
    def transform(self, ctx: TransformContext, lines: list[str], idx: int) -> bool:
        if (m204_m := M204_S_RE.match(ctx.current_line) if 1 <= ctx.layer_count <= M204_CAP_LAYERS else None):
            cap_accel = ctx.profile["first_layer_accel"]
            if int(m204_m.group(1)) > cap_accel:
                ctx.out.append(
                    re.sub(r"(M204\s+)S\d+", rf"\g<1>S{cap_accel}", ctx.current_line, count=1, flags=re.I)
                    + ctx.builder.cap_accel_suffix()
                )
                ctx.actions.append(f"m204_cap_l{ctx.layer_count}")
            else:
                ctx.out.append(ctx.current_line)
            return True
        return False


class FanCapTransformer(ILineTransformer):
    def transform(self, ctx: TransformContext, lines: list[str], idx: int) -> bool:
        fan_m = FAN_ON_RE.match(ctx.current_line)
        if ctx.in_startup and fan_m and int(fan_m.group(1)) > 0:
            ctx.out.append(ctx.builder.fan_startup_off())
            ctx.actions.append("fan_off_startup")
            return True
        if ctx.layer_fan_cap is not None and fan_m and not ctx.boost_fan and int(fan_m.group(1)) > ctx.layer_fan_cap:
            ctx.out.append(ctx.builder.fan_capped(ctx.layer_fan_cap))
            ctx.actions.append("fan_cap")
            return True
        return False


class SpeedCapTransformer(ILineTransformer):
    def transform(self, ctx: TransformContext, lines: list[str], idx: int) -> bool:
        fan_m = FAN_ON_RE.match(ctx.current_line)
        f_cap = ctx.speed_tuner.speed_cap_for(ctx.surface_kind, ctx.layer_count, ctx.in_startup, ctx.profile)
        if (
            ctx.current_upper.startswith("G1")
            and " E" in ctx.current_upper
            and G1_EXTRUDE_RE.match(ctx.current_line)
            and not fan_m
            and f_cap is not None
        ):
            new_line, capped, last_f = ctx.speed_tuner.cap_f_line(ctx.current_line, f_cap, ctx.last_f, ctx.builder)
            ctx.out.append(new_line)
            if capped:
                ctx.actions.append(f"cap_f_l{ctx.layer_count or 'startup'}")
            return True
        return False


class GCodeTransformerPipeline:
    def __init__(self, transformers: list[ILineTransformer]):
        self.transformers = transformers

    def transform(self, lines: list[str], ctx: TransformContext) -> None:
        for i, line in enumerate(lines):
            if i in ctx.skip_fan_at:
                continue

            ctx.update_line(line.rstrip("\n\r"))
            handled = False
            for transformer in self.transformers:
                if transformer.transform(ctx, lines, i):
                    handled = True
                    break
            
            if not handled:
                ctx.out.append(ctx.current_line)


def transform_gcode(
    lines: list[str],
    *,
    skip_overhang_fan: bool = False,
    prusa_cfg: dict[str, str] | None = None,
) -> tuple[list[str], list[str]]:
    bundle = get_bundle_config()
    profile = build_e5s1_profile(prusa_cfg, bundle)
    pa_fw = resolve_pa_firmware("\n".join(lines[:PA_PROBE_LINES]))
    
    builder = GCodeBuilder(pa_fw)
    ctx = TransformContext(profile, builder, skip_overhang_fan)
    
    pipeline = GCodeTransformerPipeline([
        SpeedTrackingTransformer(),
        StartupLineTransformer(),
        HeaderTransformer(),
        FeatureTypeTransformer(),
        IroningFanTransformer(),
        LayerBoundaryTransformer(),
        AccelCapTransformer(),
        FanCapTransformer(),
        SpeedCapTransformer(),
    ])
    
    pipeline.transform(lines, ctx)

    out, repair_actions = repair_gcode(ctx.out, profile, pa_fw)
    ctx.actions.extend(repair_actions)
    out = strip_pp_lines(out)
    out, pa_action = inject_pa(out, pa_fw, profile["pa_k"], builder)
    if pa_action:
        ctx.actions.append(pa_action)
    return out, ctx.actions
